routes/web.php
<?php

Route::get('/', function () {
    return redirect('admin');
});
Auth::routes();

Route::middleware(['auth'])->group(function () {
    # Change Company
    Route::get('/changeCompany/{id}', 'MasterController@changeCompany')->name('changeCompany');

    # Dashboard
    Route::get('', 'DashboardController@index')->name('data');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    # Complaints
    Route::get('/complaints/data', 'ComplaintController@data')->name('complaints.data');
    Route::resource('/complaints', 'ComplaintController');

    # Pm
    Route::get('/pm/data', 'PmController@data')->name('pm.data');
    Route::resource('/pm', 'PmController');

    # Checklist
    Route::get('/checklist/data', 'ChecklistController@data')->name('checklist.data');
    Route::resource('/checklist', 'ChecklistController');

    # Devices
    Route::get('/devices/data', 'DeviceController@data')->name('devices.data');
    Route::resource('/devices', 'DeviceController');

    # Suppliers
    Route::get('/suppliers/data', 'SupplierController@data')->name('suppliers.data');
    Route::resource('/suppliers', 'SupplierController');

    # ServiceProviders
    Route::get('/service_providers/data', 'ServiceProviderController@data')->name('service_providers.data');
    Route::resource('/service_providers', 'ServiceProviderController');

    # Manufacturers
    Route::get('/manufacturers/data', 'ManufacturerController@data')->name('manufacturers.data');
    Route::resource('/manufacturers', 'ManufacturerController');

    # Spare Parts
    Route::get('/spare_parts/data', 'SparePartController@data')->name('spare_parts.data');
    Route::resource('/spare_parts', 'SparePartController');

    # Accessories
    Route::get('/accessories/data', 'AccessoryController@data')->name('accessories.data');
    Route::resource('/accessories', 'AccessoryController');

    # Tutorials
    Route::get('/tutorials/data', 'TutorialController@data')->name('tutorials.data');
    Route::resource('/tutorials', 'TutorialController');

    # Departments
    Route::get('/departments/data', 'DepartmentController@data')->name('departments.data');
    Route::resource('/departments', 'DepartmentController');

    # Tutorials
    Route::get('/users/data', 'UserController@data')->name('users.data');
    Route::resource('/users', 'UserController');

    # Reports
    Route::get('/reports', 'ReportController@index')->name('report.index');

    # Demo
    Route::get('/{demopage?}', 'DemoController@demo')->name('demo');
    Route::get('/home', 'HomeController@index')->name('home');

    # Test Notifications
    Route::get('/notify', 'NotificationController@index')->name('notify');

    #Custom Route
    Route::any('/devices/{id}/create-pm', 'DeviceController@createPM')->name('devices.create-pm');

    Route::any('/complaints/{id}/log', 'ComplaintController@log')->name('complaints.log');

    Route::any('/pms/{id}/log', 'PmController@log')->name('pms.log');

    Route::any('/complaints/{id}/comment', 'ComplaintController@comment')->name('complaints.comment');

    Route::any('/complaints/{id}/progress', 'ComplaintController@progress')->name('complaints.progress');

    Route::any('/pms/{id}/progress', 'PmController@progress')->name('pms.progress');

});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Department
 *
 * @property-read \App\Models\Company $company
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property int $company_id
 * @property int $status_id
 * @property int $updated_by
 * @property \Illuminate\Support\Carbon $created_at
 * @property \Illuminate\Support\Carbon $updated_at
 * @property string $deleted_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Department whereCompanyId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Department whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Department whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Department whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Department whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Department whereStatusId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Department whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Department whereUpdatedBy($value)
 */
class Department extends Model
{
	protected $fillable = [
        'name',
        'company_id',
        'status_id',
        'updated_by'
    ];

    # Scope for Company based fetch
    public function scopeCompanyFetch($query)
    {
        return $query->where('company_id', session('company_id', defaultCompany()));
    }

    # Relation with Color Collection
    public function company() {
        return $this->belongsTo(Company::class);
    }


}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreDepartment;
use Illuminate\Support\Facades\Redirect;
use Yajra\Datatables\Datatables;
use App\Services\DepartmentService as Service;
use Illuminate\Http\Request;
/**
 * Class DepartmentController
 * @package App\Http\Controllers
 */
class DepartmentController extends Controller
{
    /**
     * @var Service $service
     */
    private $service;

    /**
     * DepartmentController constructor.
     * @param Service $service
     */
    public function __construct(Service $service)
    {
        $this->service = $service;
    }

    /**
     * Get Data
     * @return mixed
     * @throws \Exception
     */
    public function data()
    {
        try {
            $get = $this->service->getAll();
            return Datatables::of($get)
                ->addColumn('actions', function ($data) {
                    $html = '<a href="javascript:void(0);" data-delete="' . $data->id . '" class="btn btn-danger btn-sm btn-icon btn-icon-mini btn-round">';
                    if (!is_null($data->deleted_at))
                        $html .= '<i class="fa fa-recycle"  aria-hidden="true"></i>';
                    else
                        $html .= '<i class="fa fa-trash-o"  aria-hidden="true"></i>';

                    $html .= '</a>  &nbsp; ';
                    $html .= '<a href="#" onclick="viewEdit(' . $data->id . ')" class="btn btn-primary btn-sm btn-icon btn-icon-mini btn-round">';
                    $html .= '<i class="fa fa-pencil-square-o" data-name="edit" title="Edit" aria-hidden="true"></i>';
                    $html .= '</a>  &nbsp; ';
                    $html .= '<a href="javascript:void(0);" class="btn btn-success btn-sm btn-icon btn-icon-mini btn-round">';
                    $html .= '<i data-toggle="modal" data-target=".show" class="fa fa-eye" data-name="view"  data-view="' . $data->id . '" title="View data"  aria-hidden="true"></i> ';
                    $html .= '</a> &nbsp; ';
                    return $html;
                })
                ->addColumn('updated_at', function ($get) {
                    return $get->updated_at->diffForHumans();
                })
                ->rawColumns(['actions'])->make(true);
        } catch (\Exception $e) {
            throw $e;
        }

    }

    /**
     * Listing Department
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function index()
    {
        try {
            return view('admin.department.index');
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * Create Department
     * @throws \Throwable
     */
    public function create()
    {
        try {
            $html = "";
            $data = $this->service->getMetaData();
            $data['companies'] = $this->service->companies();
            $html .= view('admin.department.create', $data)->render();
            $response = ['status' => 201, 'data' => $html];
            echo json_encode($response);
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * Display
     * @param $id
     * @throws \Throwable
     */
    public function show($id)
    {
        try {
            $html = "";
            $data['get'] = $this->service->get($id);
            $html .= view('admin.department.view', $data)->render();
            $response = ['status' => 201, 'data' => $html];
            echo json_encode($response);
        } catch (\Exception $e) {
            throw $e;
        }

    }

    /**
     * Storing Department
     * @param StoreDepartment $department
     * @return mixed
     * @throws \Exception
     */
    public function store(Request $department)
    {
        try {
            $this->service->store($department->except("_token"));
        } catch (\Exception $e) {
            throw $e;
        }
        # Return to the Ad listing view
        return Redirect::route('departments.index')->withSuccess('New Department Added !!');
    }


    /**
     * API for getting a Single Department
     * @param $id
     * @throws \Throwable
     */
    public function edit($id)
    {
        try {
            $html = "";
            $data = $this->service->getMetaData();
            $data['get'] = $this->service->get($id);
            $data['companies'] = $this->service->companies();
            $html .= view('admin.department.edit', $data)->render();
            $response = ['status' => 201, 'data' => $html];
            echo json_encode($response);
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * API for Updating a Single Department
     * @param StoreDepartment $department
     * @param $id
     * @return mixed
     * @throws \Exception
     */
    public function update(Request $department, $id)
    {
        try {
            $this->service->update($department->except("_token"), $id);
        } catch (\Exception $e) {
            throw $e;
        }
        # Return to the Ad listing view
        return Redirect::route('departments.index')->withSuccess('New Department Added !!');
    }

    /**
     * API for Deleting a Departments
     * @param $id
     * @throws \Exception
     */
    public function destroy($id)
    {
        try {
            $this->service->destroy($id);
            $response = ['status' => 201, 'data' => 'deleted'];
            echo json_encode($response);
        } catch (\Exception $e) {
            throw $e;
        }
    }

}

resources/views/admin/department/create.blade.php
<div class="modal-header bg-info">
    <h4 class="title" id="largeModalLabel" style="color: #fff;">Add Department</h4>
    <button type="button" class="close" data-dismiss="modal" data-backdrop="false" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
    <div class="modal-body">
        <div class="row">
                <div class="col-12">
                    <form class="form-group company-form" role="form" method="post"
                                  action="{{ route('departments.store') }}"
                                  enctype="multipart/form-data" autocomplete="off">
                                @csrf
                                <div class="tab-pane fade show active" id="infoPanel" role="tabpanel">
                                    <div class="form-group form-row col-sm-12">
                                        <div class="col">
                                            <label for="name" class="control-label">Name*</label>
                                            <input type="text" id="name" name="name" class="form-control"
                                                   placeholder="Name" max="50">
                                        </div>
                                        <div class="col">
                                            <label for="company" class="control-label">Company</label>
                                            <select class="form-control" name="company_id" id="company">
                                                <option value="" selected>Select Company</option>
                                                @foreach ($companies as $value)
                                                    <option value="{{ $value->id }}">{{ $value->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-info btn-round btn-block" id="activate">Add
                                        Department
                                    </button>
                                </div>
                            </form>
            </div>
        </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">CLOSE</button>
</div>

resources/views/admin/department/edit.blade.php
<div class="modal-header bg-info">
    <h4 class="title" id="largeModalLabel" style="color: #fff;">Edit Department</h4>
    <button type="button" class="close" data-dismiss="modal" data-backdrop="false" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="row">
                        <div class="col-12">
                            <form class="form-group company-form" role="form" method="POST"
                                  action="{{ route('departments.update', $get->id) }}"
                                  enctype="multipart/form-data" autocomplete="off">
                                @csrf
                                @method('PUT')
                                <div class="tab-pane fade show active" id="infoPanel" role="tabpanel">
                                    <div class="form-group form-row col-sm-12">
                                        <div class="col">
                                            <label for="name" class="control-label">Name*</label>
                                            <input type="text" id="name" name="name" class="form-control"
                                                   value="{{$get->name}}" max="50">
                                        </div>
                                        <div class="col">
                                            <label for="company" class="control-label">Location</label>
                                            <select class="form-control" name="company_id" id="company">
                                                <option value="" selected>Select Company</option>
                                                @foreach ($companies as $value)
                                                    <option value="{{ $value->id }}" {{ $value->id == $get->company_id ? 'selected="selected"' : ''}}>
                                                        {{ $value->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-info btn-round btn-block" id="activate">Update
                                        Department
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">CLOSE</button>
</div>

resources/views/admin/department/index.blade.php
@extends('layouts.app')
@section('title', 'Department')
@section('page-style')

@section('content')
<!-- Basic Examples -->
<style type="text/css">
    #create:hover{
        color: #fff;
    }
</style>
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card">
            <div class="header" style="margin-bottom: 10px;">
                <h2><strong>Department</strong> </h2>
                <ul class="header-dropdown">
                    <button id="create" type="button" class="btn bg-pink" onclick="viewCreate()">Add +
                    </button>
                </ul>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-sm table-bordered table-striped table-hover js-basic-example dataTable" style="width: 100%;">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Company</th>
                                <th>Updated</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('page-script')
    <script>

        // DataTable
        $(document).ready(function () {
            $('.dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('departments.data') }}',
                columns: [
                    {data: 'name', name: 'name'},
                    {data: 'company.name', name: 'company.name'},
                    {data: 'updated_at', name: 'updated_at'},
                    {data: 'actions', name: 'actions', searchable: false}
                ]
            });
        });


        // View Department
        $(document).on('click', '[data-view]', function () {
            var id = $(this).attr('data-view');
            if (Number($(this).attr('data-view')) > 0) {
                viewDepartment(id);
            }
        });
        var device;

        function viewDepartment(id) {
            if (typeof(id) !== "undefined") {
                if (id > 0) {
                    if (typeof device !== 'undefined')
                        device.abort();
                    device = $.ajax({
                        type: 'GET',
                        url: "departments/" + id,
                        dataType: 'JSON',
                        async: true,
                        beforeSend: function () {
                            if (typeof device !== 'undefined')
                                device.abort();
                        },
                        success: function (response) {
                            $('#showData').html(response.data);
                            $('.showModal').modal('show');
                        }
                    });
                }
            }
        }

        // View Create Page

        function viewCreate() {
            if (typeof device !== 'undefined')
                device.abort();
            device = $.ajax({
                type: 'GET',
                url: "departments/create/",
                dataType: 'JSON',
                async: true,
                beforeSend: function () {
                    if (typeof device !== 'undefined')
                        device.abort();
                },
                success: function (response) {
                    $('#showData').html(response.data);
                    $('.showModal').modal('show');
                }
            });
        }

        // View Edit Page

        function viewEdit(id) {
            if (typeof device !== 'undefined')
                device.abort();
            device = $.ajax({
                type: 'GET',
                url: "departments/" + id + "/edit",
                dataType: 'JSON',
                async: true,
                beforeSend: function () {
                    if (typeof device !== 'undefined')
                        device.abort();
                },
                success: function (response) {
                    $('#showData').html(response.data);
                    $('.showModal').modal('show');
                }
            });
        }

        // Delete Department

        $(document).on('click', '[data-delete]', function () {
            var ele = $(this);
            var id = $(this).attr('data-delete');
            if (Number($(this).attr('data-delete')) > 0) {
                deleteDepartment(id, ele);
            }
        });

        // Toastr             toastr["error"](" cannot be Empty", "");

        function deleteDepartment(id, ele) {
            var msgTxt;
            var msgTitle;
            if (ele.find('i').hasClass('fa-recycle')) {
                msgTxt = "Department Activated";
                msgTitle = "Are you sure you want to activate ";
            } else {
                msgTxt = "Department Deleted";
                msgTitle = "Are you sure you want to delete ";
            }
            swal({
                title: msgTitle,
                text: "This device will be disabled and removed from listing.",
                type: "error",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {
                setTimeout(function () {
                    if (typeof device !== 'undefined')
                        device.abort();
                    device = $.ajax({
                        type: 'DELETE',
                        url: "departments/" + id,
                        dataType: 'JSON',
                        async: true,
                        beforeSend: function () {
                            if (typeof device !== 'undefined')
                                device.abort();
                        },
                        success: function (response) {
                            if (response.status === 201) {
                                if (ele.find('i').hasClass('fa-recycle')) {
                                    ele.find('i').attr('class', 'fa fa-trash-o').attr('title', 'Delete Department');
                                    swal({title: "Department deletion failed", type: "success"});
                                } else {
                                    ele.find('i').attr('class', 'fa fa-recycle').attr('title', 'Activate Department');
                                    swal({title: "Department deletion failed", type: "success"});
                                }
                                swal({title: msgTxt, type: "success"});
                            } else {
                                swal({title: "Department deletion failed", type: "error"});
                            }
                        }
                    });
                }, 1000);
            });
        }
    </script>
@endsection

resources/views/admin/department/view.blade.php
<div class="modal-header bg-info">
    <h4 class="title" id="largeModalLabel" style="color: #fff">Department Informations</h4>
    <button type="button" class="close" data-dismiss="modal" data-backdrop="false" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="row">
                <div class="col-12">
                    <div class="tab-pane fade show active" id="infoPanel" role="tabpanel">
                            <div class="form-group form-row col-sm-12">
                                <div class="col">
                                    <label for="name" class="control-label">Name*</label>
                                    <input type="text" id="name" name="name" class="form-control"
                                               value="{{$get->name}}"
                                               max="50" disabled>
                                </div>
                                <div class="col">
                                    <label for="company" class="control-label">Company</label>
                                    <input type="text" id="company" name="company" class="form-control"
                                               value="{{$get->company->name}}" max="50" disabled>
                                </div>
                            </div>
                    </div>
                </div>
        </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">CLOSE</button>
</div>