routes/web.php
<?php

Route::get('/', function () {
    return redirect('admin');
});
Auth::routes();

Route::middleware(['auth'])->group(function () {
    # Change Company
    Route::get('/changeCompany/{id}', 'MasterController@changeCompany')->name('changeCompany');

    # Dashboard
    Route::get('', 'DashboardController@index')->name('data');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    # Complaints
    Route::get('/complaints/data', 'ComplaintController@data')->name('complaints.data');
    Route::resource('/complaints', 'ComplaintController');

    # Pm
    Route::get('/pm/data', 'PmController@data')->name('pm.data');
    Route::resource('/pm', 'PmController');

    # Checklist
    Route::get('/checklist/data', 'ChecklistController@data')->name('checklist.data');
    Route::resource('/checklist', 'ChecklistController');

    # Devices
    Route::get('/devices/data', 'DeviceController@data')->name('devices.data');
    Route::resource('/devices', 'DeviceController');

    # Suppliers
    Route::get('/suppliers/data', 'SupplierController@data')->name('suppliers.data');
    Route::resource('/suppliers', 'SupplierController');

    # ServiceProviders
    Route::get('/service_providers/data', 'ServiceProviderController@data')->name('service_providers.data');
    Route::resource('/service_providers', 'ServiceProviderController');

    # Manufacturers
    Route::get('/manufacturers/data', 'ManufacturerController@data')->name('manufacturers.data');
    Route::resource('/manufacturers', 'ManufacturerController');

    # Spare Parts
    Route::get('/spare_parts/data', 'SparePartController@data')->name('spare_parts.data');
    Route::resource('/spare_parts', 'SparePartController');

    # Accessories
    Route::get('/accessories/data', 'AccessoryController@data')->name('accessories.data');
    Route::resource('/accessories', 'AccessoryController');

    # Tutorials
    Route::get('/tutorials/data', 'TutorialController@data')->name('tutorials.data');
    Route::resource('/tutorials', 'TutorialController');

    # Departments
    Route::get('/departments/data', 'DepartmentController@data')->name('departments.data');
    Route::resource('/departments', 'DepartmentController');

    # Tutorials
    Route::get('/users/data', 'UserController@data')->name('users.data');
    Route::resource('/users', 'UserController');

    # Reports
    Route::get('/reports', 'ReportController@index')->name('report.index');

    # Demo
    Route::get('/{demopage?}', 'DemoController@demo')->name('demo');
    Route::get('/home', 'HomeController@index')->name('home');

    # Test Notifications
    Route::get('/notify', 'NotificationController@index')->name('notify');

    #Custom Route
    Route::any('/devices/{id}/create-pm', 'DeviceController@createPM')->name('devices.create-pm');

    Route::any('/complaints/{id}/log', 'ComplaintController@log')->name('complaints.log');

    Route::any('/pms/{id}/log', 'PmController@log')->name('pms.log');

    Route::any('/complaints/{id}/comment', 'ComplaintController@comment')->name('complaints.comment');

    Route::any('/complaints/{id}/progress', 'ComplaintController@progress')->name('complaints.progress');

    Route::any('/pms/{id}/progress', 'PmController@progress')->name('pms.progress');

});

app/Models/Manufacturer.php
<?php

namespace App\Models;

use App\Traits\ModelSignature;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Manufacturer extends Model
{
    use SoftDeletes;
    use ModelSignature;

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    protected $guarded = ['id'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'location',
        'email',
        'phone',
        'status_id',
        'updated_by'
    ];

}

app/Http/Controllers/ManufacturerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreManufacturer;
use Illuminate\Support\Facades\Redirect;
use Yajra\Datatables\Datatables;
use App\Services\ManufacturerService as Service;
use Illuminate\Http\Request;

/**
 * Class ManufacturerController
 * @package App\Http\Controllers
 */
class ManufacturerController extends Controller
{
    /**
     * @var Service $service
     */
    private $service;

    /**
     * ManufacturerController constructor.
     * @param Service $service
     */
    public function __construct(Service $service)
    {
        $this->service = $service;
    }

    /**
     * Get Data
     * @return mixed
     * @throws \Exception
     */
    public function data()
    {
        try {
            $get = $this->service->getAll();
            return Datatables::of($get)
                ->addColumn('actions', function ($data) {
                    $html = '<a href="javascript:void(0);" data-delete="' . $data->id . '" class="btn btn-danger btn-sm btn-icon btn-icon-mini btn-round">';
                    if (!is_null($data->deleted_at))
                        $html .= '<i class="fa fa-recycle"  aria-hidden="true"></i>';
                    else
                        $html .= '<i class="fa fa-trash-o"  aria-hidden="true"></i>';

                    $html .= '</a>  &nbsp; ';
                    $html .= '<a href="#" onclick="viewEdit(' . $data->id . ')" class="btn btn-primary btn-sm btn-icon btn-icon-mini btn-round">';
                    $html .= '<i class="fa fa-pencil-square-o" data-name="edit" title="Edit" aria-hidden="true"></i>';
                    $html .= '</a>  &nbsp; ';
                    $html .= '<a href="javascript:void(0);" class="btn btn-success btn-sm btn-icon btn-icon-mini btn-round">';
                    $html .= '<i data-toggle="modal" data-target=".show" class="fa fa-eye" data-name="view"  data-view="' . $data->id . '" title="View data"  aria-hidden="true"></i> ';
                    $html .= '</a> &nbsp; ';
                    return $html;
                })
                ->addColumn('updated_at', function ($get) {
                    return $get->updated_at->diffForHumans();
                })
                ->rawColumns(['actions'])->make(true);
        } catch (\Exception $e) {
            throw $e;
        }

    }

    /**
     * Listing Manufacturer
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function index()
    {
        try {
            return view('admin.manufacturer.index');
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * Create Manufacturer
     * @throws \Throwable
     */
    public function create()
    {
        try {
            $html = "";
            $html .= view('admin.manufacturer.create')->render();
            $response = ['status' => 201, 'data' => $html];
            echo json_encode($response);
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * Display
     * @param $id
     * @throws \Throwable
     */
    public function show($id)
    {
        try {
            $html = "";
            $data['get'] = $this->service->get($id);
            $html .= view('admin.manufacturer.view', $data)->render();
            $response = ['status' => 201, 'data' => $html];
            echo json_encode($response);
        } catch (\Exception $e) {
            throw $e;
        }

    }

    /**
     * Storing Manufacturer
     * @param StoreManufacturer $manufacturer
     * @return mixed
     * @throws \Exception
     */
    public function store(Request $manufacturer)
    {
        try {
            $this->service->store($manufacturer->except("_token"));
        } catch (\Exception $e) {
            throw $e;
        }
        # Return to the Ad listing view
        return Redirect::route('manufacturers.index')->withSuccess('New Manufacturer Added !!');
    }


    /**
     * API for getting a Single Manufacturer
     * @param $id
     * @throws \Throwable
     */
    public function edit($id)
    {
        try {
            $html = "";
            $data['get'] = $this->service->get($id);
            $html .= view('admin.manufacturer.edit', $data)->render();
            $response = ['status' => 201, 'data' => $html];
            echo json_encode($response);
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * API for Updating a Single Manufacturer
     * @param StoreManufacturer $manufacturer
     * @param $id
     * @return mixed
     * @throws \Exception
     */
    public function update(Request $manufacturer, $id)
    {
        try {
            $this->service->update($manufacturer->except("_token"), $id);
        } catch (\Exception $e) {
            throw $e;
        }
        # Return to the Ad listing view
        return Redirect::route('manufacturers.index')->withSuccess('New Manufacturer Added !!');
    }

    /**
     * API for Deleting a Manufacturers
     * @param $id
     * @throws \Exception
     */
    public function destroy($id)
    {
        try {
            $this->service->destroy($id);
            $response = ['status' => 201, 'data' => 'deleted'];
            echo json_encode($response);
        } catch (\Exception $e) {
            throw $e;
        }
    }

}

resources/views/admin/manufacturer/create.blade.php
<div class="modal-header bg-info">
    <h4 class="title" id="largeModalLabel" style="color: #fff;">Add Manufacturer</h4>
    <button type="button" class="close" data-dismiss="modal" data-backdrop="false" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
    <div class="modal-body">
        <div class="row">
                <div class="col-12">
                    <form class="form-group company-form" role="form" method="post"
                                  action="{{ route('manufacturers.store') }}"
                                  enctype="multipart/form-data" autocomplete="off">
                                @csrf
                                <div class="tab-pane fade show active" id="infoPanel" role="tabpanel">
                                    <div class="form-group form-row col-sm-12">
                                        <div class="col">
                                            <label for="name" class="control-label">Name*</label>
                                            <input type="text" id="name" name="name" class="form-control"
                                                   placeholder="Name" max="50">
                                        </div>
                                        <div class="col">
                                            <label for="location" class="control-label">Location</label>
                                            <input type="text" id="location" name="location" class="form-control"
                                                   placeholder="Location" max="50">
                                        </div>
                                    </div>

                                    <div class="form-group form-row col-sm-12">
                                        <div class="col">
                                            <label for="email" class="control-label">Email</label>
                                            <input type="email" id="email" name="email" class="form-control"
                                                   placeholder="Email" max="190">
                                        </div>
                                        <div class="col">
                                            <label for="phone" class="control-label">Phone</label>
                                            <input type="tel" id="phone" name="phone" class="form-control"
                                                   placeholder="Phone" max="190">
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-info btn-block btn-round" id="activate">Add
                                        Manufacturer
                                    </button>
                                </div>
                            </form>
            </div>
        </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">CLOSE</button>
</div>

resources/views/admin/manufacturer/edit.blade.php
<div class="modal-header bg-info">
    <h4 class="title" id="largeModalLabel" style="color: #fff;">Edit Manufacturer</h4>
    <button type="button" class="close" data-dismiss="modal" data-backdrop="false" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="row">
                        <div class="col-12">
                            <form class="form-group company-form" role="form" method="POST"
                                  action="{{ route('manufacturers.update', $get->id) }}"
                                  enctype="multipart/form-data" autocomplete="off">
                                @csrf
                                @method('PUT')
                                <div class="tab-pane fade show active" id="infoPanel" role="tabpanel">
                                    <div class="form-group form-row col-sm-12">
                                        <div class="col">
                                            <label for="name" class="control-label">Name*</label>
                                            <input type="text" id="name" name="name" class="form-control"
                                                   value="{{$get->name}}" max="50">
                                        </div>
                                        <div class="col">
                                            <label for="location" class="control-label">Location</label>
                                            <input type="text" id="location" name="location" class="form-control"
                                                   value="{{$get->location}}" max="50">
                                        </div>
                                    </div>

                                    <div class="form-group form-row col-sm-12">
                                        <div class="col">
                                            <label for="email" class="control-label">Email</label>
                                            <input type="email" id="email" name="email" class="form-control"
                                                   value="{{$get->email}}" max="190">
                                        </div>
                                        <div class="col">
                                            <label for="phone" class="control-label">Phone</label>
                                            <input type="tel" id="phone" name="phone" class="form-control"
                                                   value="{{$get->phone}}" max="190">
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-info btn-block btn-round" id="activate">Update
                                        Manufacturer
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">CLOSE</button>
</div>

resources/views/admin/manufacturer/index.blade.php
@extends('layouts.app')
@section('title', 'Manufacturers')
@section('page-style')

@section('content')
<!-- Basic Examples -->
<style type="text/css">
    #create:hover{
        color: #fff;
    }
</style>
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card">
            <div class="header" style="margin-bottom: 10px;">
                <h2><strong>Manufacturers</strong> </h2>
                <ul class="header-dropdown">
                    <button id="create" type="button" class="btn bg-pink" onclick="viewCreate()">Add +
                    </button>
                </ul>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-sm table-bordered table-striped table-hover js-basic-example dataTable" style="width: 100%;">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Location</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Updated</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('page-script')

<script>

        // DataTable
        $(document).ready(function () {
            $('.dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('manufacturers.data') }}',
                columns: [
                    {data: 'name', name: 'name'},
                    {data: 'location', name: 'location'},
                    {data: 'email', name: 'email'},
                    {data: 'phone', name: 'phone'},
                    {data: 'updated_at', name: 'updated_at'},
                    {data: 'actions', name: 'actions', searchable: false}
                ]
            });
        });


        // View Manufacturer
        $(document).on('click', '[data-view]', function () {
            var id = $(this).attr('data-view');
            if (Number($(this).attr('data-view')) > 0) {
                viewManufacturer(id);
            }
        });
        var device;

        function viewManufacturer(id) {
            if (typeof(id) !== "undefined") {
                if (id > 0) {
                    if (typeof device !== 'undefined')
                        device.abort();
                    device = $.ajax({
                        type: 'GET',
                        url: "manufacturers/" + id,
                        dataType: 'JSON',
                        async: true,
                        beforeSend: function () {
                            if (typeof device !== 'undefined')
                                device.abort();
                        },
                        success: function (response) {
                            $('#showData').html(response.data);
                            $('.showModal').modal('show');
                        }
                    });
                }
            }
        }

        // View Create Page

        function viewCreate() {
            if (typeof device !== 'undefined')
                device.abort();
            device = $.ajax({
                type: 'GET',
                url: "manufacturers/create/",
                dataType: 'JSON',
                async: true,
                beforeSend: function () {
                    if (typeof device !== 'undefined')
                        device.abort();
                },
                success: function (response) {
                    $('#showData').html(response.data);
                    $('.showModal').modal('show');
                }
            });
        }

        // View Edit Page

        function viewEdit(id) {
            if (typeof device !== 'undefined')
                device.abort();
            device = $.ajax({
                type: 'GET',
                url: "manufacturers/" + id + "/edit",
                dataType: 'JSON',
                async: true,
                beforeSend: function () {
                    if (typeof device !== 'undefined')
                        device.abort();
                },
                success: function (response) {
                    $('#showData').html(response.data);
                    $('.showModal').modal('show');
                }
            });
        }

        // Delete Manufacturer

        $(document).on('click', '[data-delete]', function () {
            var ele = $(this);
            var id = $(this).attr('data-delete');
            if (Number($(this).attr('data-delete')) > 0) {
                deleteManufacturer(id, ele);
            }
        });

        // Toastr             toastr["error"](" cannot be Empty", "");

        function deleteManufacturer(id, ele) {
            var msgTxt;
            var msgTitle;
            if (ele.find('i').hasClass('fa-recycle')) {
                msgTxt = "Manufacturer Activated";
                msgTitle = "Are you sure you want to activate ";
            } else {
                msgTxt = "Manufacturer Deleted";
                msgTitle = "Are you sure you want to delete ";
            }
            swal({
                title: msgTitle,
                text: "This device will be disabled and removed from listing.",
                type: "error",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {
                setTimeout(function () {
                    if (typeof device !== 'undefined')
                        device.abort();
                    device = $.ajax({
                        type: 'DELETE',
                        url: "manufacturers/" + id,
                        dataType: 'JSON',
                        async: true,
                        beforeSend: function () {
                            if (typeof device !== 'undefined')
                                device.abort();
                        },
                        success: function (response) {
                            if (response.status === 201) {
                                if (ele.find('i').hasClass('fa-recycle')) {
                                    ele.find('i').attr('class', 'fa fa-trash-o').attr('title', 'Delete Manufacturer');
                                    swal({title: "Manufacturer deletion failed", type: "success"});
                                } else {
                                    ele.find('i').attr('class', 'fa fa-recycle').attr('title', 'Activate Manufacturer');
                                    swal({title: "Manufacturer deletion failed", type: "success"});
                                }
                                swal({title: msgTxt, type: "success"});
                            } else {
                                swal({title: "Manufacturer deletion failed", type: "error"});
                            }
                        }
                    });
                }, 1000);
            });
        }
    </script>
@endsection

resources/views/admin/manufacturer/view.blade.php
<div class="modal-header bg-info">
    <h4 class="title" id="largeModalLabel" style="color: #fff">Manufacturer Details</h4>
    <button type="button" class="close" data-dismiss="modal" data-backdrop="false" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-12">
                            <div class="tab-pane fade show active" id="infoPanel" role="tabpanel">
                                <div class="form-group form-row col-sm-12">
                                    <div class="col">
                                        <label for="name" class="control-label">Name*</label>
                                        <input type="text" id="name" name="name" class="form-control"
                                               value="{{$get->name}}"
                                               max="50" disabled>
                                    </div>
                                    <div class="col">
                                        <label for="location" class="control-label">Location</label>
                                        <input type="text" id="location" name="location" class="form-control"
                                               value="{{$get->location}}" max="50" disabled>
                                    </div>
                                </div>

                                <div class="form-group form-row col-sm-12">
                                    <div class="col">
                                        <label for="email" class="control-label">Email</label>
                                        <input type="email" id="email" name="email" class="form-control"
                                               value="{{$get->email}}"
                                               max="190" disabled>
                                    </div>
                                    <div class="col">
                                        <label for="phone" class="control-label">Phone</label>
                                        <input type="tel" id="phone" name="phone" class="form-control"
                                               value="{{$get->phone}}"
                                               max="190" disabled>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">CLOSE</button>
</div>